@DependsUpon(packagesOf = {
        com.github.t1.graph.Graph.class,
        com.github.t1.xml.Xml.class,

        ch.qos.logback.classic.Logger.class,
        com.sun.tools.classfile.Dependency.class,
        com.sun.tools.jdeps.ClassFileReader.class,
        org.assertj.core.api.Assertions.class,
        org.assertj.core.description.Description.class,
        org.glassfish.hk2.api.Factory.class,
        org.glassfish.jersey.logging.LoggingFeature.class,
        org.jboss.as.controller.client.Operation.class,
        org.jboss.as.controller.client.helpers.Operations.class,
        org.jboss.dmr.ModelNode.class,
        org.jboss.shrinkwrap.api.ShrinkWrap.class,
        org.jboss.shrinkwrap.api.asset.FileAsset.class,
        org.jboss.shrinkwrap.api.exporter.ZipExporter.class,
        org.jboss.shrinkwrap.api.spec.WebArchive.class,
        org.jboss.shrinkwrap.resolver.api.Resolvers.class,
        org.jboss.shrinkwrap.resolver.api.maven.Maven.class,
        org.junit.Test.class,
        org.junit.rules.RunRules.class,
        org.junit.runner.Runner.class,
        org.junit.runners.Parameterized.class,
        org.junit.runners.model.FrameworkMethod.class,
        org.openqa.selenium.WebDriver.class,
        org.openqa.selenium.htmlunit.HtmlUnitDriver.class,
        org.openqa.selenium.interactions.Action.class,
        org.openqa.selenium.logging.Logs.class,
        org.openqa.selenium.support.PageFactory.class,
        org.openqa.selenium.support.ui.WebDriverWait.class,
        org.wildfly.swarm.Swarm.class,
        org.wildfly.swarm.spi.api.Fraction.class,
        org.wildfly.swarm.spi.api.config.Resolver.class,
})
package com.github.t1.testtools;
